name: Hola Mundo Workflow

on:
  push:
    branches:
      - master

jobs:
  hello_world:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Imprimir Hola Mundo
      run: echo "Hola, mundo"
