name: Hola Mundo Workflow

on:
  push:
    branches:
      - master

jobs:
  hello_world:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Imprimir Hola Mundo
      run: echo "Hola, mundo"
      
    - name: Guardar variable como secret
      run: |
        echo "value of secret: ${{ secrets.MY_SECRET }}"
        ENV_JSON='${{ secrets.MY_SECRET }}'
        echo "$ENV_JSON" | jq -r 'to_entries[] | "\(.key)=\(.value)"' >> $GITHUB_ENV
